apiVersion: v1
kind: Service
metadata:
  name: kubernetes-hello-world
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    group: org.springframework.cloud
    project: kubernetes-hello-world
    provider: fabric8
  sessionAffinity: None
  type: NodePort
