spring:
  application:
    name: greeting-service

server:
  port: 8080

backend:
  ribbon:
    eureka:
      enabled: false
    client:
       enabled: true
    # We will use Spring Cloud Kubernetes Ribbon to retrieve the list of the servers
    # listOfServers: backend:8080
    ServerListRefreshInterval: 15000

hystrix.command.BackendCall.execution.isolation.thread.timeoutInMilliseconds: 30000
hystrix.threadpool.BackendCallThread.coreSize: 5